# Generated by Django 5.0.1 on 2024-01-24 09:02

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredient_1_amount', models.FloatField(default=0.0)),
                ('ingredient_2_amount', models.FloatField(default=0.0)),
                ('ingredient_3_amount', models.FloatField(default=0.0)),
                ('ingredient_4_amount', models.FloatField(default=0.0)),
                ('ingredient_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_1', to='cocktail.ingredient')),
                ('ingredient_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_2', to='cocktail.ingredient')),
                ('ingredient_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_3', to='cocktail.ingredient')),
                ('ingredient_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_4', to='cocktail.ingredient')),
            ],
        ),
    ]
