# Generated by Django 5.0.1 on 2024-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='ingredient_2_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredient_3_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredient_4_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
