# Generated by Django 5.0.1 on 2024-01-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_alter_cocktail_ingredient_2_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='ice',
            field=models.BooleanField(default=False),
        ),
    ]
